### PR TITLE
remove

### PR DESCRIPTION
**Pull request by maryrsmcphee**
more testsss

### CODE REVIEW

**Review by SammyRobensParadise — APPROVED** [review]

**Comment by SammyRobensParadise** [comment]
looks good, does this contain a fix at all?

**Comment by maryrsmcphee** [comment]
doesn't fix it completely but does help some obvious little errors

**Comment by SammyRobensParadise** [comment]
okay feel free to merge

**Comment by SammyRobensParadise** [comment]
thanks!!

**Comment by maryrsmcphee** [comment]
i can take out the things i did for testing if you want and then merge or if you want the other tests commented out I can merge it now

i commented some stuff out to narrow down the problem which might be annoying or helpful lol

**Pull request merged**
